[themes.OceanLight.style]
AntiAliasedLines = true
WindowRounding = 8.0
FrameRounding = 6.0
ItemSpacing = [8.0, 4.0]
FramePadding = [8.0, 8.0]

[themes.OceanLight.colors]
Text = "#212121"
WindowBg = [0.95, 0.95, 0.97, 1.0] # You can use arrays (0.0 to 1.0)
Button = "#1E88E5"                 # Or HEX colors
ButtonHovered = "#25A0F9"


# Classic Steam style by metasprite from ImThemes
[themes.ClassicSteam.style]
Alpha = 1.0
DisabledAlpha = 0.6
WindowPadding = [8.0, 8.0]
WindowRounding = 0.0
WindowBorderSize = 1.0
WindowMinSize = [32.0, 32.0]
WindowTitleAlign = [0.0, 0.5]
WindowMenuButtonPosition = "Left"
ChildRounding = 0.0
ChildBorderSize = 1.0
PopupRounding = 0.0
PopupBorderSize = 1.0
FramePadding = [4.0, 3.0]
FrameRounding = 0.0
FrameBorderSize = 1.0
ItemSpacing = [8.0, 4.0]
ItemInnerSpacing = [4.0, 4.0]
CellPadding = [4.0, 2.0]
IndentSpacing = 21.0
ColumnsMinSpacing = 6.0
ScrollbarSize = 14.0
ScrollbarRounding = 0.0
GrabMinSize = 10.0
GrabRounding = 0.0
TabRounding = 0.0
TabBorderSize = 0.0
TabMinWidthForCloseButton = 0.0
ColorButtonPosition = "Right"
ButtonTextAlign = [0.5, 0.5]
SelectableTextAlign = [0.0, 0.0]
[themes.ClassicSteam.colors]
Text = "#FFFFFFFF"
TextDisabled = "#7F7F7FFF"
WindowBg = "#495642FF"
ChildBg = "#495642FF"
PopupBg = "#3D4433FF"
Border = "#89918280"
BorderShadow = "#23281C85"
FrameBg = "#3D4433FF"
FrameBgHovered = "#444C3AFF"
FrameBgActive = "#4C5642FF"
TitleBg = "#3D4433FF"
TitleBgActive = "#495642FF"
TitleBgCollapsed = "#00000082"
MenuBarBg = "#3D4433FF"
ScrollbarBg = "#596B4FFF"
ScrollbarGrab = "#47513DFF"
ScrollbarGrabHovered = "#3F4C38FF"
ScrollbarGrabActive = "#3A4435FF"
CheckMark = "#96892DFF"
SliderGrab = "#596B4FFF"
SliderGrabActive = "#89918280"
Button = "#49564266"
ButtonHovered = "#596B4FFF"
ButtonActive = "#89918280"
Header = "#596B4FFF"
HeaderHovered = "#596B4F99"
HeaderActive = "#89918280"
Separator = "#23281CFF"
SeparatorHovered = "#899182FF"
SeparatorActive = "#96892DFF"
ResizeGrip = "#303A2D00"
ResizeGripHovered = "#899182FF"
ResizeGripActive = "#96892DFF"
Tab = "#596B4FFF"
TabHovered = "#899182C7"
TabActive = "#96892DFF"
TabUnfocused = "#3D4433FF"
TabUnfocusedActive = "#596B4FFF"
PlotLines = "#9B9B9BFF"
PlotLinesHovered = "#96892DFF"
PlotHistogram = "#FFC647FF"
PlotHistogramHovered = "#FF9900FF"
TableHeaderBg = "#303033FF"
TableBorderStrong = "#4F4F59FF"
TableBorderLight = "#3A3A3FFF"
TableRowBg = "#00000000"
TableRowBgAlt = "#FFFFFF0F"
TextSelectedBg = "#96892DFF"
DragDropTarget = "#BAAA3DFF"
NavHighlight = "#96892DFF"
NavWindowingHighlight = "#FFFFFFB3"
NavWindowingDimBg = "#CCCCCC33"
ModalWindowDimBg = "#CCCCCC59"
