#!/usr/bin/env python3
import os
import re
import argparse
from collections import OrderedDict

# --- Configuration ---

# The root directory of the MUI library source
SOURCE_DIR = 'mui'

# The final output file name
OUTPUT_FILE = 'mui.hpp'

# The implementation guard macro
IMPLEMENTATION_GUARD = 'MUI_IMPLEMENTATION'

# The header guard macro
HEADER_GUARD = 'MUI_SINGLE_HEADER_HPP'

# Preamble for the generated file (license, etc.)
PREAMBLE = """// MUI Single-Header Library
// Generated by create_single_header.py
//
// To use this library, do this in one C++ file:
// #define MUI_IMPLEMENTATION
// #include "mui.hpp"
//
// In other files, just include the header:
// #include "mui.hpp"
//
// It is recommended to build the implementation file with a high optimization level.
"""

# List of stb-style single-header libraries to handle specially.
# Their content will be included in the header, and their implementation
# will be included in the implementation block.
STB_STYLE_LIBRARIES = {
    'stb_image.h': 'STB_IMAGE_IMPLEMENTATION',
    'imstb_textedit.h': 'IMSTB_TEXTEDIT_IMPLEMENTATION',
}

# --- Main Logic ---

def get_file_list(root_dir):
    """Walks the source directory to find all .hpp, .h, and .cpp files."""
    headers = []
    sources = []
    stb_files = []
    for root, _, files in os.walk(root_dir):
        for file in files:
            path = os.path.join(root, file)
            if file in STB_STYLE_LIBRARIES:
                stb_files.append(path)
            elif file.endswith('.hpp') or file.endswith('.h'):
                headers.append(path)
            elif file.endswith('.cpp'):
                sources.append(path)

    headers.sort()
    sources.sort()
    stb_files.sort()
    return headers, sources, stb_files

def process_file(filepath, local_headers_set, source_dir):
    """
    Reads a file and separates its content from its include directives.
    Skips includes that are part of the library itself.
    """
    content = []
    system_includes = set()

    # Regex to find include statements, ignoring any trailing comments.
    include_regex = re.compile(r'#\s*include\s*([<"])(.*?)([>"])')

    file_dir = os.path.dirname(filepath)

    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            for line in f:
                # Skip #pragma once
                if line.strip() == '#pragma once':
                    continue

                match = include_regex.match(line.strip())
                if match:
                    delimiter = match.group(1)
                    header_name = match.group(2)

                    is_local_and_merged = False
                    if delimiter == '"':
                        # For local includes ("header.h"), we need to check if they are part of
                        # the library we are merging. We do this by resolving the path.
                        # 1. Get the absolute path of the included file relative to the current file.
                        abs_include_path = os.path.normpath(os.path.join(file_dir, header_name))
                        # 2. Get its path relative to the project root to match the format in `local_headers_set`.
                        #    The `os.path.dirname(source_dir) or '.'` part handles cases where source_dir is in the current directory.
                        rel_include_path = os.path.normpath(os.path.relpath(abs_include_path, os.path.dirname(source_dir) or '.'))

                        if rel_include_path in local_headers_set:
                             is_local_and_merged = True

                    if is_local_and_merged:
                        # Skip this include, its content will be in the final file
                        content.append(f"// SKIPPED: {line.strip()}\n")
                    else:
                        # This is a system include or an external library include.
                        # Use match.group(0) to get just the '#include <...>' part, without trailing comments.
                        system_includes.add(match.group(0))
                else:
                    content.append(line)
    except Exception as e:
        print(f"[-] Error processing file {filepath}: {e}")
        return None, None

    return "".join(content), system_includes

def main():
    parser = argparse.ArgumentParser(description="Create a single-header C++ library from a source tree.")
    parser.add_argument("source_dir", nargs='?', default=SOURCE_DIR, help="The root directory of the library source code.")
    parser.add_argument("output_file", nargs='?', default=OUTPUT_FILE, help="The path for the generated single-header file.")
    args = parser.parse_args()

    print(f"[*] Source directory: {args.source_dir}")
    print(f"[*] Output file: {args.output_file}")

    if not os.path.isdir(args.source_dir):
        print(f"[-] Error: Source directory '{args.source_dir}' not found.")
        return

    header_files, source_files, stb_files = get_file_list(args.source_dir)

    # Treat stb files as both headers (for declarations) and special implementation files
    all_headers_to_process = sorted(header_files + stb_files)

    print("\n[+] Found header files to merge:")
    for h in all_headers_to_process:
        print(f"  - {h}")

    print("\n[+] Found source files to merge:")
    for s in source_files:
        print(f"  - {s}")

    # Create a set of normalized relative paths for quick checking
    local_header_paths_set = {os.path.normpath(os.path.relpath(h, os.path.dirname(args.source_dir) or '.')) for h in all_headers_to_process}

    all_system_includes = OrderedDict()
    all_header_content = []
    all_source_content = []

    print("\n[*] Processing headers...")
    for header_path in all_headers_to_process:
        content, includes = process_file(header_path, local_header_paths_set, args.source_dir)
        if content is not None:
            all_header_content.append(f"// --- Content from {os.path.relpath(header_path)} ---\n\n{content}\n")
            for inc in includes:
                all_system_includes[inc] = None

    print("\n[*] Processing sources...")
    for source_path in source_files:
        content, includes = process_file(source_path, local_header_paths_set, args.source_dir)
        if content is not None:
            all_source_content.append(f"// --- Content from {os.path.relpath(source_path)} ---\n\n{content}\n")
            for inc in includes:
                all_system_includes[inc] = None

    # Special handling for stb-style headers
    all_stb_content = OrderedDict()
    if stb_files:
        print("\n[*] Reading stb-style headers to embed in implementation:")
        for stb_path in stb_files:
            print(f"  - {stb_path}")
            try:
                with open(stb_path, 'r', encoding='utf-8', errors='ignore') as f:
                    all_stb_content[os.path.basename(stb_path)] = f.read()
            except Exception as e:
                print(f"[-] Could not read {stb_path}: {e}")

    print("\n[*] Assembling final header file...")
    with open(args.output_file, 'w', encoding='utf-8') as f:
        # 1. Preamble and Header Guard
        f.write(PREAMBLE)
        f.write(f"\n#ifndef {HEADER_GUARD}\n")
        f.write(f"#define {HEADER_GUARD}\n\n")

        # 2. System Includes (deduplicated)
        f.write("// --- System and External Library Includes ---\n")
        for inc in all_system_includes.keys():
            f.write(inc + "\n")
        f.write("\n")

        # 3. Header Content
        f.write("// ===================================================================================\n")
        f.write("//                                 HEADER PART\n")
        f.write("// ===================================================================================\n\n")
        for content in all_header_content:
            f.write(content)
            f.write("\n")

        # 4. Implementation Guard
        f.write(f"\n#ifdef {IMPLEMENTATION_GUARD}\n\n")
        f.write("// ===================================================================================\n")
        f.write("//                              IMPLEMENTATION PART\n")
        f.write("// ===================================================================================\n\n")

        # 5. stb-style header implementations
        if all_stb_content:
            f.write("// --- Begin stb-style header implementations ---\n")
            for name, content in all_stb_content.items():
                if name in STB_STYLE_LIBRARIES:
                    f.write(f"#define {STB_STYLE_LIBRARIES[name]}\n")
                f.write(content)
                f.write(f"\n// --- End {name} ---\n\n")

        # 6. Source Content
        for content in all_source_content:
            f.write(content)
            f.write("\n")

        # 7. End Implementation Guard
        f.write(f"\n#endif // {IMPLEMENTATION_GUARD}\n")

        # 8. End Header Guard
        f.write(f"\n#endif // {HEADER_GUARD}\n")

    print(f"\n[+] Successfully created single-header library at '{args.output_file}'")

if __name__ == '__main__':
    main()