#include "style_parser_utils.hpp"
#include <cstdio> // For sscanf

namespace mui
{

    // Shared mappings for ImGuiCol and ImGuiStyleVar
    const std::unordered_map<std::string_view, ImGuiCol, ci_hash, ci_equal> colorMap = {
        {"text", ImGuiCol_Text},
        {"textdisabled", ImGuiCol_TextDisabled},
        {"windowbg", ImGuiCol_WindowBg},
        {"childbg", ImGuiCol_ChildBg},
        {"popupbg", ImGuiCol_PopupBg},
        {"border", ImGuiCol_Border},
        {"bordershadow", ImGuiCol_BorderShadow},
        {"framebg", ImGuiCol_FrameBg},
        {"framebghovered", ImGuiCol_FrameBgHovered},
        {"framebgactive", ImGuiCol_FrameBgActive},
        {"titlebg", ImGuiCol_TitleBg},
        {"titlebgactive", ImGuiCol_TitleBgActive},
        {"titlebgcollapsed", ImGuiCol_TitleBgCollapsed},
        {"menubarbg", ImGuiCol_MenuBarBg},
        {"scrollbarbg", ImGuiCol_ScrollbarBg},
        {"scrollbargrab", ImGuiCol_ScrollbarGrab},
        {"scrollbargrabhovered", ImGuiCol_ScrollbarGrabHovered},
        {"scrollbargrabactive", ImGuiCol_ScrollbarGrabActive},
        {"checkmark", ImGuiCol_CheckMark},
        {"slidergrab", ImGuiCol_SliderGrab},
        {"slidergrabactive", ImGuiCol_SliderGrabActive},
        {"button", ImGuiCol_Button},
        {"buttonhovered", ImGuiCol_ButtonHovered},
        {"buttonactive", ImGuiCol_ButtonActive},
        {"header", ImGuiCol_Header},
        {"headerhovered", ImGuiCol_HeaderHovered},
        {"headeractive", ImGuiCol_HeaderActive},
        {"separator", ImGuiCol_Separator},
        {"separatorhovered", ImGuiCol_SeparatorHovered},
        {"separatoractive", ImGuiCol_SeparatorActive},
        {"resizegrip", ImGuiCol_ResizeGrip},
        {"resizegriphovered", ImGuiCol_ResizeGripHovered},
        {"resizegripactive", ImGuiCol_ResizeGripActive},
        {"inputtextcursor", ImGuiCol_InputTextCursor},
        {"tab", ImGuiCol_Tab},
        {"tabhovered", ImGuiCol_TabHovered},
        {"tabactive", ImGuiCol_TabActive},
        {"tabselected", ImGuiCol_TabSelected}, // Alias for TabActive
        {"tabdimmed", ImGuiCol_TabDimmed},
        {"tabdimmedselected", ImGuiCol_TabDimmedSelected},
        {"tabdimmedselectedoverline", ImGuiCol_TabDimmedSelectedOverline},
        {"tabunfocused", ImGuiCol_TabUnfocused},
        {"tabunfocusedactive", ImGuiCol_TabUnfocusedActive},
        {"dockingpreview", ImGuiCol_DockingPreview},
        {"dockingemptybg", ImGuiCol_DockingEmptyBg},
        {"plotlines", ImGuiCol_PlotLines},
        {"plotlineshovered", ImGuiCol_PlotLinesHovered},
        {"plothistogram", ImGuiCol_PlotHistogram},
        {"plothistogramhovered", ImGuiCol_PlotHistogramHovered},
        {"tableheaderbg", ImGuiCol_TableHeaderBg},
        {"tableborderstrong", ImGuiCol_TableBorderStrong},
        {"tableborderlight", ImGuiCol_TableBorderLight},
        {"tablerowbg", ImGuiCol_TableRowBg},
        {"tablerowbgalt", ImGuiCol_TableRowBgAlt},
        {"textlink", ImGuiCol_TextLink},
        {"textselectedbg", ImGuiCol_TextSelectedBg},
        {"dragdroptarget", ImGuiCol_DragDropTarget},
        {"dragdroptargetbg", ImGuiCol_DragDropTargetBg},
        {"navcursor", ImGuiCol_NavCursor},
        {"navhighlight", ImGuiCol_NavHighlight},
        {"navwindowinghighlight", ImGuiCol_NavWindowingHighlight},
        {"navwindowingdimbg", ImGuiCol_NavWindowingDimBg},
        {"modalwindowdimbg", ImGuiCol_ModalWindowDimBg},
        {"treelines", ImGuiCol_TreeLines},
        {"unsavedmarker", ImGuiCol_UnsavedMarker},
        {"windowbg", ImGuiCol_WindowBg},
    };

    const std::unordered_map<std::string_view, ImGuiStyleVar, ci_hash, ci_equal> styleVarMap = {
        {"alpha", ImGuiStyleVar_Alpha},
        {"buttontextalign", ImGuiStyleVar_ButtonTextAlign},
        {"cellpadding", ImGuiStyleVar_CellPadding},
        {"childbordersize", ImGuiStyleVar_ChildBorderSize},
        {"childrounding", ImGuiStyleVar_ChildRounding},
        {"disabledalpha", ImGuiStyleVar_DisabledAlpha},
        {"dockingseparatorsize", ImGuiStyleVar_DockingSeparatorSize},
        {"framebordersize", ImGuiStyleVar_FrameBorderSize},
        {"framepadding", ImGuiStyleVar_FramePadding},
        {"framerounding", ImGuiStyleVar_FrameRounding},
        {"grabminsize", ImGuiStyleVar_GrabMinSize},
        {"grabrounding", ImGuiStyleVar_GrabRounding},
        {"imagebordersize", ImGuiStyleVar_ImageBorderSize},
        {"imagerounding", ImGuiStyleVar_ImageRounding},
        {"indentspacing", ImGuiStyleVar_IndentSpacing},
        {"iteminnerspacing", ImGuiStyleVar_ItemInnerSpacing},
        {"itemspacing", ImGuiStyleVar_ItemSpacing},
        {"popupbordersize", ImGuiStyleVar_PopupBorderSize},
        {"popuprounding", ImGuiStyleVar_PopupRounding},
        {"scrollbarpadding", ImGuiStyleVar_ScrollbarPadding},
        {"scrollbarrounding", ImGuiStyleVar_ScrollbarRounding},
        {"scrollbarsize", ImGuiStyleVar_ScrollbarSize},
        {"selectabletextalign", ImGuiStyleVar_SelectableTextAlign},
        {"separatorsize", ImGuiStyleVar_SeparatorSize},
        {"separatortextalign", ImGuiStyleVar_SeparatorTextAlign},
        {"separatortextbordersize", ImGuiStyleVar_SeparatorTextBorderSize},
        {"separatortextpadding", ImGuiStyleVar_SeparatorTextPadding},
        {"tabbarbordersize", ImGuiStyleVar_TabBarBorderSize},
        {"tabbaroverlinesize", ImGuiStyleVar_TabBarOverlineSize},
        {"tabbordersize", ImGuiStyleVar_TabBorderSize},
        {"tabminwidthbase", ImGuiStyleVar_TabMinWidthBase},
        {"tabminwidthshrink", ImGuiStyleVar_TabMinWidthShrink},
        {"tabrounding", ImGuiStyleVar_TabRounding},
        {"tableangledheadersangle", ImGuiStyleVar_TableAngledHeadersAngle},
        {"tableangledheaderstextalign", ImGuiStyleVar_TableAngledHeadersTextAlign},
        {"treelinesrounding", ImGuiStyleVar_TreeLinesRounding},
        {"treelinessize", ImGuiStyleVar_TreeLinesSize},
        {"windowbordersize", ImGuiStyleVar_WindowBorderSize},
        {"windowminsize", ImGuiStyleVar_WindowMinSize},
        {"windowpadding", ImGuiStyleVar_WindowPadding},
        {"windowrounding", ImGuiStyleVar_WindowRounding},
        {"windowtitlealign", ImGuiStyleVar_WindowTitleAlign},
    };

} // namespace mui